# fly.toml app configuration file generated for api-cors on 2023-05-16T13:42:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "api-cors"
primary_region = "sin"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
